In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
iris = pd.read_csv("/content/archive (8).zip")

In [3]:
print(iris.shape)

(150, 6)


In [4]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [27]:
print(iris.isnull().sum())

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64


In [6]:
iris.Species

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [7]:
iris.describe

<bound method NDFrame.describe of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-se

In [8]:
### CLASSIFYING THE FLOWER TYPES USING LabelEncoder()
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(iris.Species)
iris['Species'] = le.transform(iris.Species)
print(iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]


In [9]:
print(iris.Species)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64


In [10]:
# STANDARDIZING THE DATA USING STANDARDSCALER
x = iris.iloc[:,0:4]
y = iris.iloc[:,4]
x

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0      1            5.1           3.5            1.4
1      2            4.9           3.0            1.4
2      3            4.7           3.2            1.3
3      4            4.6           3.1            1.5
4      5            5.0           3.6            1.4
..   ...            ...           ...            ...
145  146            6.7           3.0            5.2
146  147            6.3           2.5            5.0
147  148            6.5           3.0            5.2
148  149            6.2           3.4            5.4
149  150            5.9           3.0            5.1

[150 rows x 4 columns]

In [11]:
y

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ... 
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: PetalWidthCm, Length: 150, dtype: float64

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc = sc.fit(x)
x = sc.transform(x)
x

array([[-1.72054204, -0.90068117,  1.03205722, -1.3412724 ],
       [-1.69744751, -1.14301691, -0.1249576 , -1.3412724 ],
       [-1.67435299, -1.38535265,  0.33784833, -1.39813811],
       [-1.65125846, -1.50652052,  0.10644536, -1.2844067 ],
       [-1.62816394, -1.02184904,  1.26346019, -1.3412724 ],
       [-1.60506942, -0.53717756,  1.95766909, -1.17067529],
       [-1.58197489, -1.50652052,  0.80065426, -1.3412724 ],
       [-1.55888037, -1.02184904,  0.80065426, -1.2844067 ],
       [-1.53578584, -1.74885626, -0.35636057, -1.3412724 ],
       [-1.51269132, -1.14301691,  0.10644536, -1.2844067 ],
       [-1.4895968 , -0.53717756,  1.49486315, -1.2844067 ],
       [-1.46650227, -1.26418478,  0.80065426, -1.227541  ],
       [-1.44340775, -1.26418478, -0.1249576 , -1.3412724 ],
       [-1.42031323, -1.87002413, -0.1249576 , -1.51186952],
       [-1.3972187 , -0.05250608,  2.18907205, -1.45500381],
       [-1.37412418, -0.17367395,  3.11468391, -1.2844067 ],
       [-1.35102965, -0.

In [13]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.70, random_state=10)


In [14]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [15]:
print(y_train.unique())


[0.1 1.5 1.8 2.  2.5 1.  0.2 1.4 1.7 1.1 2.4 2.1 0.3 1.2 1.6 2.3 1.3 0.4
 1.9 2.2 0.5]


In [16]:
y_train = y_train.astype(int)


In [17]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors = 7)
neigh.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [18]:
y_pred = neigh.predict(x_test)

In [19]:
y_pred[:10]

array([1, 1, 0, 1, 0, 1, 1, 1, 0, 1])

In [20]:
print(y_test[0:10])

87     1.3
111    1.9
10     0.2
91     1.4
49     0.2
60     1.0
72     1.5
67     1.0
39     0.2
55     1.3
Name: PetalWidthCm, dtype: float64


In [21]:
print(y_test.dtypes)
print(y_test.unique())


float64
[1.3 1.9 0.2 1.4 1.  1.5 0.3 2.1 1.6 0.4 2.2 1.8 1.2 2.4 2.3 0.6]


In [22]:
y_test = y_test.astype(int)


In [23]:
import sklearn.metrics as metrics
confusion = metrics.confusion_matrix(y_true=y_test,y_pred=y_pred)
confusion


array([[14,  0,  0],
       [ 0, 21,  1],
       [ 0,  4,  5]])

In [24]:
metrics.accuracy_score(y_true=y_test,y_pred=y_pred)

0.8888888888888888

In [25]:
class_wise = metrics.classification_report(y_true=y_test,y_pred=y_pred)
print(class_wise)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.84      0.95      0.89        22
           2       0.83      0.56      0.67         9

    accuracy                           0.89        45
   macro avg       0.89      0.84      0.85        45
weighted avg       0.89      0.89      0.88        45

